### ISSUE TITLE
Can not use spaces in names

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/discord#5]
Describe the bug
The discord bot that shows player stats cannot handle spaces in names properly

To Reproduce
Go to #bot-commands
Use k!user "Blank blank-2333"
Returns improperly formatted

Expected behavior
Quotation marks should pass wrapped text as a single parameter.

**Comment by DefinitelyNotJah** [comment]
This issue is more of an enhancement type than a bug type.
The discord bot can handle spaces just fine (check screenshot down below), however when it comes to text wrapped in quotation marks **"**, obviously not.
it really is unnecessary to add support for quotation marks since there are no keyma.sh users with spaces in their usernames/tags. 
![2021-08-23_22-34](https://user-images.githubusercontent.com/63221794/130522900-df6ac950-2985-42e1-a626-a0a87b94af17.png)

**Comment by Syndric** [comment]
There are some users who have spaces in their names ATM (me included)

**Comment by Syndric** [comment]
@diamonddev01 The best solution is to change your name to no spaces, get your roles, then change back to spaces. BTW k!user doesn't work if you have spaces

**Comment by diamonddev01** [comment]
Yeah I did, I also put a fix in the pull requests

**Comment by Syndric** [comment]
Fixed in #16
